services:
  mongodb:
    image: mongo:latest
    container_name: tds-mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: tds-website
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
